excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- MinterWallet/Third Party
- MinterWallet/Classes/Common/Helper/Storyboards.swift
- .*Test\\.swift
- .*Tests\\.swift
- MinterWalletUITests
- MinterWalletTests
